apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-deploy
  labels:
    app: website
spec:
  replicas: 2
  selector: 
    matchlabel:
    app: website
  template:
   metadata:
     labels:
       app: website
   spec:
     containers:
     - name: web
       image: nginx
       ports:
       - containerPort: 80